graph:  
  nodes:
    - 0
    - 1
    - 2
  # 0 == die, 1 == reward. 
  edges:
    - from: 2
      to: 1
    - from: 2
      to: 0
  start_node: 2

initial_image: ./initial_images/1.png
agent_num: 1
